modLoader="javafml"
loaderVersion="[43,)"
license="Unlicense"
[[mods]]
modId="blahaj"
version="0.1.7"
displayName="Blåhaj - Restitched"
displayURL="https://modrinth.com/mod/blahaj-restitched"
logoFile="icon.png"
credits="Made by Dogatorix"
authors="Original Blåhaj mod by hibi, ported to Forge by agnor99, continued by Dogatorix"

description='''
Soft toy, shark mod, 16px.
'''
[[dependencies.blahaj]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blahaj]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
